### ISSUE TITLE
template/init.lua:19: table index is nil

### ISSUE THREAD

**Issue by yutkat** [glepnir/template.nvim#12]
I have encountered the following error.

```
Error detected while processing LspAttach Autocommands for "*":
Error executing lua callback: ...ocal/share/nvim/lazy/template.nvim/lua/template/init.lua:22: table index is nil
```

It seems the sh filetype is not correctly detected.
`~/.config/nvim/template/bash.sh`

This command doesn't work either.
```lua
vim.filetype.match({ filename = `main.sh` })
```

If it is main.zsh, it is detected as zsh.

**Comment by glepnir** [comment]
looks like if use `filename` it only can match the filename like `.bashrc .zshrc` . the quickly way is use 
```lua
vim.filetype.add ( filename = { ['main.zsh'] = 'zsh' })
```

**Comment by yutkat** [comment]
Thank you. I added it and solved this problem.
