### ISSUE TITLE
Templates insert carriage return ^M

### ISSUE THREAD

**Issue by xiugaze** [glepnir/template.nvim#23]
Hi,
My templates are inserting a character literal ^M after each line. Is this expected behavior, and is there a way to disable this?

**Comment by glepnir** [comment]
not expected behavior.  what template you used. I can test it .

**Comment by xiugaze** [comment]
[core.md](https://github.com/glepnir/template.nvim/files/10421265/core.md)

thanks, this is the one i'm using
