### ISSUE TITLE
Telescope to import template in existing file

### ISSUE THREAD

**Issue by ned-si** [glepnir/template.nvim#24]
At the moment, when selecting a template using `:Telescope find_template`, it creates a new file with the template name as file name. 

Would it be possible to select a template with Telescope and have it in an existing file in the same way that `:Template <template-name>` work?

Love your plugin!

**Comment by glepnir** [comment]
update and try `Telescope find_template name=test_aa.lua`

**Comment by ned-si** [comment]
Just updated.

I tried in a new `test.lua` file and when I type `Telescope find_template name=nvim-keymap.lua` as you asked:
- It opens `Telescope find_template` as if I didn't specified any name afterwards
- If select a template and then `<CR>`, it still creates a new file with the template name and the template inside
- On the other hand, `:Template ` still works fine (except `{{_cursor_}}`.

**Comment by ned-si** [comment]
Any idea if it could still be implemented at some point?

Love to use the plugin in general the regular way, but this functionality would make it perfect :)

**Comment by glepnir** [comment]
doc had write . `Telescope find_template type=insert` then select template it will insert.

**Comment by ned-si** [comment]
Oh sorry, I was just following this issue and didn't see it, thanks a lot, amazing!
