### ISSUE TITLE
I am so very lost and confused, and I am getting the error message `template.nvim does not get filetype from template dir`.

### ISSUE THREAD

**Issue by anoduck** [glepnir/template.nvim#31]
Admittedly, this plugin makes me feel stupid, or that there is some memo on how to use it that I missed.

I understand how to set up this plugin for packer to install it, but I am unsure where the entire "projects" block/glob is supposed to go. It is as follows:

```lua
use {
    "glepnir/template.nvim",
        config = function()
	require("template").setup {
		temp_dir = '~/.config/nvim/templates',
		author = 'Anoduck',
		email = 'anoduck@github.com',
		project = {
			['website'] = {
	   		    ['lang'] = {
				['html'] = {
					'index.html',
					'.gitignore',
					}
				}
			},
			['shell'] = {
				['lang'] = {
					['bash'] = {
						'script.sh',
						}
					}
				},
			['other'] = {
				'README.md',
				'.gitignore',
				}
			},
		}
	end
}
```

I am not sure why project is being defined, but I assume this is just confusion over semantics.

I also don't know why I am recieving the error, `template.nvim does not get filetype from template dir`. 

Is there a working configuration example available? It may help to clear up the confusion.

**Comment by glepnir** [comment]
you don't need project `field` it works for `TemProject` command. for template you don't need config it . get this error mean template does not get any template in your temp dir.

**Comment by anoduck** [comment]
I gotcha now. Understandable, because I haven't written any templates yet. Nice...well done template. I love your nvim setup. Thanks for clarify things for me. Cheers.

**Comment by anoduck** [comment]
@glepnir You have the sweetest Neovim setup I have seen yet. Epic job!

**Comment by glepnir** [comment]
my neovim config or something else ?

**Comment by anoduck** [comment]
> my neovim config or something else ?

Primarily your configuration and start page. The logo is quite impressive. Your status line is impressive as well. It is all well done.
