### ISSUE TITLE
How to use template files in project templates?

### ISSUE THREAD

**Issue by derekthecool** [glepnir/template.nvim#33]
This plugin is wonderful for creating project templates.

But I have two questions about how to fine tune the project templates filenames and contents.

For example, I have this set for my `project` configuration.

```lua
            project = {
                ['test'] = {
                    ['lang'] = {
                        ['lua'] = {
                            ['lua'] = {
                                'plugin.lua',
                            },
                            ['tests'] = {
                                'plugin_spec.lua',
                            },
                        },
                    },
                },
            },
```

This is my basic starter template for neovim plugins. Here are the two questions I have on this:

1. Can I prompt for filenames in here? I've tried using a filename such as `{{_variable_}}.lua` but that literally names the file with those letters and no replacement is done.
I would really like to be prompted for the name of the `plugin.lua` filename and then reuse that for the test file name. That would look something like this `{{_plugin_name_}}_spec.lua` (or any possible way to reference that filename

2. How can I specify a template file for these project level items? As far as I can tell the single file templates and these project templates are completely separate.

**Comment by glepnir** [comment]
a new think about create project.. I prefer to write a cli tool implement this.. not in neovim plugin.
