### ISSUE TITLE
[Enhancement] Use a template extension instead of the actual filetype

### ISSUE THREAD

**Issue by akinsho** [glepnir/template.nvim#9]
Writing a template with invalid syntax causes the file to have show up with diagnostic errors and syntax highlighting errors etc. Would you consider using something like `main.go.template` so that the file type isn't triggered as go and that LSPs and syntax highlighting don't explode.

Alternatively, this plugin could automatically register an autocommand on `BufRead` of the template dir files and use `vim.diagnostic.disable` but this won't disable weird syntax highlighting.

**Comment by glepnir** [comment]
good question. I had think about use a new extension to avoid the diagnostic and i found i just edit template once or twice. so I think i can ignore diagnostic . there has two ways

- use `tmpl` or `tpl` extension
- like you said. use autocmd filetype check file path string if match template dir then disable diagnostic. I think this way you can do it on your config

**Comment by akinsho** [comment]
@glepnir so I added the second way in my config but tbh I still have a bunch of treesitter syntax errors and disabling via `vim.diagnostic` does not turn off everything. Also I just think fundamentally the file isn't a valid `x` filetype so should not behave as a filetype. I think looking at a file in my templates' directory in my config in nvim should show up without the same highlighting. Would be nice if there was template highlighting but tbh this is completely out of scope

**Comment by glepnir** [comment]
looks like works fine with me .  currently I work on lspsaga outline (80%) when I finished I will recheck it .
![template](https://user-images.githubusercontent.com/41671631/178248612-30df99cd-e92c-4b4f-adad-ba957ad7a628.gif)

**Comment by akinsho** [comment]
@glepnir I guess you disable `TSError` highlight, but I don't so that still shows up, also in your screenshot you will notice that even after you `disable` your statusline still shows the error count for the buffer.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/22454918/178249787-4cb8b029-0308-43b6-9586-2458afcae295.png">

**Comment by akinsho** [comment]
I guess I can ignore the `TSError` highlight and maybe the `vim.diagnostic` behaviour is an upstream bug. Seems like having to work around all this stuff though 🤔

**Comment by glepnir** [comment]
I think I found a way to do it .

**Comment by glepnir** [comment]
@akinsho  how do you config temp dir use os.getenv('home') or `~`

**Comment by akinsho** [comment]
Something like `vim.fn.expand('~/.dotfiles')..rest_of_the_path`

**Comment by glepnir** [comment]
Please test .should be works fine

**Comment by glepnir** [comment]
oh use `vim.diagnostic.disable` will be better

**Comment by glepnir** [comment]
it works. but statusline still show diagnostic info . maybe can ignore ?

**Comment by akinsho** [comment]
@glepnir it's really not a **big** deal, just a minor annoyance. I guess I don't spend much time in that file, it's just that all diagnostics are always present so now in my config looking at diagnostics in qf always shows errors. I'll see if there's a better way to ignore them

**Comment by glepnir** [comment]
use a new extension it will solve all problem but need add highlight for all filetype

**Comment by akinsho** [comment]
Yeah, I imagine that will be a fair bit of work maybe 🤔 maybe it can be done without syntax highlighting for the underlying filetype just using `:syntax` and highlighting only the template variables/syntax, or maybe it can inherit vim's `:syntax` for the filetype and just add extensions for the template syntax

e.g.
```vim
" syntax/template
exe 'runtime! syntax/'.ft.'.vim'
syntax match " blah blah I'm not a syntax expert 😅 
```

**Comment by akinsho** [comment]
Well, you would need to be able to inject `ft` somehow
